# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: NodeTool@0 
  inputs:
    versionSpec: '12.0'

- script: npm install
  workingDirectory: $(Build.SourcesDirectory)/ClientApp
  displayName: 'npm install'

- script: npm install -g @angular/cli
  displayName: 'install angular/cli'

- script: ng build --prod
  workingDirectory: $(Build.SourcesDirectory)/ClientApp
  displayName: 'ng build'

- task: CopyFiles@2
  inputs:
    SourceFolder: $(Build.SourcesDirectory)/ClientApp/ClientApp
    contents: '*'
    targetFolder: $(Build.ArtifactStagingDirectory)/app/ClientApp

- script: dotnet build --configuration $(buildConfiguration)
  workingDirectory: $(Build.SourcesDirectory)
  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet publish --configuration $(buildConfiguration) --output '$(Build.ArtifactStagingDirectory)/app'
  workingDirectory: $(Build.SourcesDirectory)
  displayName: 'dotnet publish $(buildConfiguration)'
- task: ArchiveFiles@2
  displayName: "Archive files"
  inputs:
    rootFolderOrFile: "$(Build.ArtifactStagingDirectory)/app"
    includeRootFolder: false
    archiveFile: "$(System.DefaultWorkingDirectory)/$(Build.BuildId).zip"
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/$(Build.BuildId).zip'
    artifactName: 'drop'
